blogs_app_fi/mysite/apps/articles/urls.py
from django.urls import path
from . import views
from .views import (
    PostUpdateView,
    PostDeleteView,
    ArticleListView,
    UserArticlesListView,
    RubricArticlesListView,
    Comment_delete, 
    Comment_update,
    PostCreateView,)
    #MyCommentDeleteView)


app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='articles_home'), #views.home_page
    path('user/<str:username>/', UserArticlesListView.as_view(), name='user_articles'), #views.home_page and accounts_views.profile
    path('about/', views.about, name = 'articles_about'),
    path('rubrics/', views.list_rubrics, name='list_rubrics'),
    path('rubrics/<slug:rubric_slug>/', RubricArticlesListView.as_view(), name='by_rubric'),
    path('articles/<slug:slug>/', views.detail, name='detail'),
    #path('articles/<slug:slug>/update', views.update_article, name='update_article'),
    path('articles/<slug:slug>/update/', PostUpdateView.as_view(), name='article_update'),
    path('articles/<slug:slug>/delete/', PostDeleteView.as_view(), name='article_delete'),
    path('articles/<int:pk>/comment_delete/', Comment_delete.as_view(), name='comment_delete'),
    path('articles/<int:pk>/comment_update/', Comment_update.as_view(), name='comment_update'),
    #path('articles/<slug:slug>/leave_comment', views.leave_comment, name='leave_comment'),
    path('create_article/', PostCreateView.as_view(), name='create_article'),
    #path('create_article/', views.create_article, name='create_article'),


]






































#{% for rubric in rubrics %}
#<menu>
#<li><a href="{% url 'by_rubric' rubric.pk %}">{{Rubric.name_of_rubric}}</a></li>
#</menu>
#{% endfor %}

#{% endblock %}

blogs_app_fi/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)
#from django.conf.urls import handler400, handler403, handler404, handler500
from django.urls import path, include
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls, name='admin'),
    
    # Password reset block
    path('password_reset/',
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password_reset_complete',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    # ending

    path('captcha/', include('captcha.urls')),

    # custom

    # articles app
    path('', include('articles.urls')),

    # accounts app
    path('profile_settings/', accounts_views.profile_settings, name='profile_settings'),
    path('signup/', accounts_views.signup_view, name='signup'),
    path('login/', accounts_views.login_view,
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
        name='logout'),
]





if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)


handler404 = 'mysite.errors.not_found'

handler400 = 'mysite.errors.bad_request'

handler500 = 'mysite.errors.server_error'

blogs_app_fi/mysite/apps/articles/models.py
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse
# from emoji_picker.widgets import EmojiPickerTextInputAdmin, EmojiPickerTextareaAdmin


class Article(models.Model):
    article_title = models.CharField('title of article', max_length = 70)
    article_text = models.TextField('text of article')
    slug = models.SlugField(unique = True)
    author_article = models.ForeignKey(User, on_delete=models.CASCADE)
    rubric = models.ForeignKey('Rubric', null = True, on_delete = models.PROTECT, blank=True)
    pub_date = models.DateTimeField('date of publication', auto_now_add = True)
    image = models.ImageField('image', blank=True, upload_to='articles_images')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 1))

    def get_absolute_url(self):
        return reverse('articles:detail', args=[self.slug])

    def snippet(self):
        if len(self.article_text) >= 500: 
            return self.article_text[:500] + '...'
        else: 
            return self.article_text

    '''class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'''

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_comment = models.ForeignKey(User, on_delete = models.CASCADE)
    comment_text = models.TextField('comment text', max_length = 800)
    pub_date = models.DateTimeField('date of publication', auto_now_add = True)

    '''def __str__(self):
        return self.author_name'''


    '''class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'''


class Rubric(models.Model):
    rubric_name = models.CharField(max_length=50, unique=True)
    rubric_slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.rubric_name

blogs_app_fi/mysite/apps/articles/forms.py
from django import forms
from . import models

'''class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['article_title', 'article_text', 'slug', 'rubric', 'image']
'''

class LeaveComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['comment_text']
        # class Media:
        #     js = ('js/enter.js', )

blogs_app_fi/mysite/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy			# USE VIRTUAL ENVIRONMENT! blogs_venv\Scripts\activate
											
from django.views.generic import CreateView

from accounts.models import Profile

from .models import (
    Article,
    Rubric,
    Comment
    )

from django.contrib.auth.decorators import login_required

from . import forms

from accounts.forms import UserUpdateForm, ProfileUpdateForm

from django.contrib import messages

from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView
)

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

#from django import forms

#from emoji_picker.widgets import EmojiPickerTextInput, EmojiPickerTextarea


class ArticleListView(ListView):
    model = Article
    ordering = ['-pub_date']
    paginate_by = 3
    template_name = 'articles/homepage.html'
    context_object_name = 'articles'


class UserArticlesListView(ArticleListView, ListView):
    template_name = 'articles/user_posts.html'
    context_object_name = 'user_articles'
    # paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(
        User,
        username=self.kwargs.get('username'))

        return Article.objects.filter(author_article=user)#.order_by('-pub_date')


def about(request):
	return render(request, 'articles/about.html')


#@login_required
def detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    last_comments_list = article.comment_set.order_by('-pub_date') # view 10 last comms
    new_comment = None
    image = article.image
    # Comment posted
    if request.method == 'POST':
        comment_form = forms.LeaveComment(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # get username
            new_comment.author_comment = request.user
            # Assign the current post to the comment
            new_comment.article = article
            # Save the comment to the database
            new_comment.save()
            messages.success(request, 'You created a comment!')
            return HttpResponseRedirect( reverse('articles:detail', args = (article.slug,))
            ) # doing it on fly, set the comment to article

    else:
        comment_form = forms.LeaveComment()

    return render(request, 'articles/detail.html', {'article': article,
                                                    'last_comments_list': last_comments_list,
                                                    'new_comment': new_comment,
                                                    'comment_form': comment_form,
                                                    'image': image})


# Rubrics Stuff

def list_rubrics(request):
	rubrics = Rubric.objects.all()
	return render(request, 'articles/list_rubrics.html', {
	'rubrics': rubrics
	})


class RubricArticlesListView(ListView):
    model = Rubric
    template_name = 'articles/by_rubric.html'
    context_object_name = 'by_rubric'
    ordering = ['-pub_date']
    paginate_by = 5

    def get_queryset(self):
        by_rubric = get_object_or_404(
        Rubric,
        #rubric_name=self.kwargs.get('rubric_name'),
        rubric_slug=self.kwargs.get('rubric_slug'))

        return Article.objects.filter(rubric_id=by_rubric).order_by('-pub_date')


class Post(LoginRequiredMixin):
    model = Article

    def form_valid(self, form):
        form.instance.author_article = self.request.user
        return super().form_valid(form)

    def test_func(self):                   #checking user
        post = self.get_object()
        if self.request.user == post.author_article:
            return True
        return False

class PostCreateView(Post, CreateView):
    fields = ['article_title', 'article_text', 'slug', 'rubric', 'image']

    def get_success_url(self):
        messages.success(self.request, 'You created an article')
        return reverse_lazy('articles:detail', kwargs={'slug': self.object.slug})


class PostUpdateView(Post, UserPassesTestMixin, UpdateView):
	fields = ['article_title', 'article_text', 'rubric', 'image']


class PostDeleteView(Post, UserPassesTestMixin, DeleteView):
    success_url = reverse_lazy('articles:articles_home')


class Comment_view(LoginRequiredMixin, UserPassesTestMixin):
    model = Comment

    def test_func(self):                   #checking user
        post = self.get_object()
        if self.request.user == post.author_comment:
            return True
        return False

class Comment_delete(Comment_view, DeleteView):

    def get_success_url(self):
        messages.error(self.request, 'You deleted a comment.')
        return reverse_lazy('articles:detail', kwargs={'slug': self.object.article.slug})


class Comment_update(Comment_view, UpdateView):
    fields = ['comment_text']

    def get_success_url(self):
        messages.info(self.request, 'You updated a comment.')
        return reverse_lazy('articles:detail', kwargs={'slug': self.object.article.slug})

    def form_valid(self, form):
        form.instance.author_comment = self.request.user
        return super().form_valid(form)

blogs_app_fi/mysite/apps/articles/templates/articles/about.html
{% extends 'base.html' %}
{% block content %}
<style>
    .you-can{
        font-size: 1.5rem;
    }
</style>
<title>About us</title>
<h1> This a site for making your blog! </h1>
<span class="you-can">
    <b>You can:</b>
    <ul>
    <li>Create posts</li>
    <li>Making your profile</li>
    <li>Watch other profiles and see many rubrics!</li>
    </ul>
</span>
{% endblock %}

blogs_app_fi/mysite/apps/articles/templates/articles/article_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<title>Delete Post ?</title>
  <div class="content-section">
      <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Delete Post</legend>
              <h2 style="word-wrap:break-word;">Are you sure you want to delete the post "{{ object.article_title }}" ?</h2>
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
              <a class="btn btn-outline-secondary" href="{% url 'articles:detail' object.slug %}">Cancel</a>
          </div>
      </form>
  </div>
{% endblock %}

blogs_app_fi/mysite/apps/articles/templates/articles/article_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
    #id_slug{
        border: none;
        display: inline;
        font-family: inherit;
        font-size: inherit;
        padding: none;
        /* pointer-events: none; */
    };


</style>
<title>Create an Article !</title>
    
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            {% if article.image %}
            <b style="font-size: 1.4rem;">Currently:</b><br><img src="{{ article.image.url }}" class="img_article"><br><br>
            {% endif %}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
    <script>
        let input_text = document.querySelector("#div_id_article_text > div")
        $(input_text).append("<button type=button class=emoji id=emoji2 style=top:-30px;right:5px;float:right;position:relative;>😎</button>")
    </script>
    <script src="{% static 'js/fgEmojiPicker.js' %}"></script>
    <script>
      new FgEmojiPicker({
            trigger: ['#emoji2'],
            position: ['bottom', 'right'],
            dir: '/static/js/',
            emit(obj, triggerElement) {
                const emoji = obj.emoji;
                document.querySelector('#id_article_text').value += emoji;
                
            }
        });
    </script>
    <script type="text/javascript">
        /*new new FgEmojiPicker({
            trigger: ['#emoji2', '#id_article_text'],
            position: ['bottom', 'right'],
            dir: '/static/js/',
            emit(obj, triggerElement) {
                const emoji = obj.emoji;
                document.querySelector('#id_article_text').value += emoji;
                
            }
        });
        new FgEmojiPicker({
            trigger: ['#emoji1'],
            position: ['bottom', 'right'],
            dir: '/static/js/',
            emit(obj, triggerElement) {
                const emoji = obj.emoji;
                document.querySelector('#id_article_title').value += emoji;
            }
        });*/
    </script>
    <script>
        // $('.fg-emoji-picker:gt(0)').remove();
    </script>
    <script>
        let image = document.querySelector("input[type=file]"); 
        image.setAttribute("multiple", "True");
        image.style = "display: none; position:absolute";  
        let currently = document.querySelector("#div_id_image > div")
        currently.style = "display:none";
        let label = document.querySelector("#div_id_image > label");
        $(label).html("<span style=color:var(--select-image)><i class=material-icons>add_photo_alternate&nbsp</i>Select an image</span>");
        label.className = "btn btn-secondary";
        label.style = "margin-bottom: -15px; font-size: 20px;";
        // let allDiv = document.querySelector("#div_id_image");
        // $(allDiv).append("<span style='margin-bottom:-10px'>Image</span>")
    </script>
    <script src="{% static 'js/slugify.js' %}"></script>
{% endblock %}

blogs_app_fi/mysite/apps/articles/templates/articles/by_rubric.html
{% extends 'base.html' %}
{% block content %}

<style>

    #asterisk{
      float: right;
    }

    #posts_by{
      text-align: center;
      margin-bottom: 20px;
    }

</style>

{% if by_rubric %}
  {% for a in by_rubric %}
  <div class="name_rubric">
  <title>{{a.rubric.rubric_name}}</title>
  <h2 id="posts_by">Posts by rubric: {{a.rubric.rubric_name}} <small><strong>
    ({{ page_obj.paginator.count }})</strong></small></h2>
  </div>
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ a.author_article.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" id="author_name" href="{% url 'articles:user_articles' a.author_article.username %}">{{ a.author_article }}</a>
        <small class="text-muted">{{ a.pub_date }}</small>
        <small class="text-muted" id="asterisk">*click on title of article to see details</small>
      </div>
    <h2><a class="article-title" href="{% url 'articles:detail' slug=a.slug %}">{{ a.article_title }}</a></h2>
    <p class="article-content">{{ a.article_text }}</p>
    </div>
  </article>
  {% endfor %}
{% else %}
    No articles found by this rubric! )=
{% endif %}

{% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}

{% endblock %}

blogs_app_fi/mysite/apps/articles/templates/articles/comment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <title>Create an Article !</title>
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
               
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
    <script src="{% static 'js/fgEmojiPicker.js' %}" ></script>
    <script>
    let inputComment = document.querySelector("#div_id_comment_text > div")
    $(inputComment).append("<button type=button class=emoji style=top:-30px;right:5px;float:right;position:relative;>😎</button>")
</script>

<script>
  new FgEmojiPicker({
            trigger: ['.emoji'],
            position: ['bottom', 'right'],
            dir: '/static/js/',
            emit(obj, triggerElement) {
                const emoji = obj.emoji;
                document.querySelector('#id_comment_text').value += emoji;
                
            }
        });
</script>
{% endblock %}

blogs_app_fi/mysite/apps/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
  .article{
    word-wrap:break-word;
    font-size: 1.2rem;
}
  .article-text{
    white-space: pre-line;
  }

  .article-title{
    font-size: 2.4rem;;
  }

  .new_article{
    float: right;
    font-size: 20px;
  }

  /* .img_article {
    max-width: 90%;
    max-height: 700px;
    position: relative;
  } */
  
  .detail_options{
    visibility: hidden;
    float: right;
    margin-right: 5px;
  }

  .options{
    float: right;
    /* margin-right: 30px; */
  }

  /* .media:hover{
    visibility: hidden;
  } */

  .media:hover .detail_options{
    visibility:visible;
  }

  #update{
    margin-left: 3px;
  }
  
  .no_comments{
    margin-top: 15px;
    font-weight: bold;
    font-size: 25px;
  }

  #comment_block{
    word-wrap:break-word;
  };

  </style>
<title>{{ article.article_title }}</title>
<section class="article">
<h2 class="article-title">{{article.article_title}}</h2>


<p class="article-text">{{article.article_text}}</p>

</section>

<span><em>Posted by <a class="mr-2" id="author_name" href="{% url 'articles:user_articles' article.author_article.username %}">
  {{ article.author_article }}</a>in {{article.pub_date}}</em></span>
  {% if article.was_published_recently %}
    <strong class='new_article'>New article!</strong>
  {% endif %}
{% if article.rubric.rubric_name %}
<br>
<small class="text-muted">More articles with rubric

  <a href="{% url 'articles:by_rubric' article.rubric.rubric_slug %}" id="author_name">{{article.rubric.rubric_name}}</a>

</small>
{% endif %}
{% if article.image %}
<div class="item">
<br>
  <img src="{{ article.image.url }}" class="img_article">
<br>
</div>
{% endif %}
<br>

{% if article.author_article == user %}
  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'articles:article_delete' article.slug %}">
    Delete</a>
  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'articles:article_update' article.slug %}">
    Update</a>
{% endif %}
<br>
<br>
{% if user.is_authenticated %}

<form method="POST" class="comment_create">
  {% csrf_token %}
  <fieldset class="form-group">
      {{ comment_form|crispy }}
  </fieldset>
  <div class="form-group">
      <button class="btn btn-outline-info" type="submit" id="comment_button">Comment</button>
  </div>
</form>

{% else %}
  <h3>You should <a id="author_name" href="{% url 'login' %}">login</a> to comment!<h3>

{% endif %}
<br>
{% if last_comments_list %}

 <h3>Comments:</h3>
  {% for comment in last_comments_list %}
  <hr>
  <div class="media">
    <img class="rounded-circle article-img" src="{{ comment.author_comment.profile.image.url }}">

      <div class="media-body">
      <p id="comment_block">{{comment.comment_text}}</p>

      <div class="mr-2" class="article-metadata"><a id="author_name" href="{% url 'articles:user_articles' comment.author_comment.username %}">{{comment.author_comment}}</a>
        <small>left a comment at <em>{{comment.pub_date}}</em>
        <!-- {% if comment_update %}
          (upd.)
        {% endif %} -->
        </small>
        <span class="options">
          {% if comment.author_comment == user %}
          <!-- <button type="submit" class="btn btn-outline-primary btn-sm mt-1 mb-1" id='three_dots'>⋮</button> -->
          <span class="detail_options">
            <a class="btn btn-outline-danger btn-sm mt-1 mb-1" id="delete" href="{% url 'articles:comment_delete' comment.id %}">
              ❌</a>
            <a class="btn btn-outline-info btn-sm mt-1 mb-1" id="update" href="{% url 'articles:comment_update' comment.id %}">
              ✍️</a>
          {% endif %}
          </span>
        </span>
      </div>
    </div>
  </div>
  
    {% endfor %}
{% else %}
<p class="no_comments">
  No comments found! Be first! =)
</p>
{% endif %}
<br><br><br><br>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
  let comment_block = document.getElementById("comment_block");
  comment_block.style.maxWidth = "300px";
 }
else{
  document.getElementById("comment_block").style.maxWidth = "650px";
  };

$(() => {
  $('#id_comment_text').on('keypress', function(e) {
    if (e.keyCode == 13) {
    $('#comment_button').click();
    };
  });
});
</script>
<script src="{% static 'js/fgEmojiPicker.js' %}"></script>
<script>
    let inputComment = document.querySelector("#div_id_comment_text > div")
    $(inputComment).append("<button type=button class=emoji style=top:-30px;right:5px;float:right;position:relative;>😎</button>")
</script>

<script>
  new FgEmojiPicker({
            trigger: ['.emoji'],
            position: ['bottom', 'right'],
            dir: '/static/js/',
            emit(obj, triggerElement) {
                const emoji = obj.emoji;
                document.querySelector('#id_comment_text').value += emoji;
                
            }
        });
</script>

{% endblock %}


<!-- <script>
$(() => {
  $('#id_comment_text').on('keypress', function(e) {
    if (e.keyCode == 13) {
      const newTask = $(this).val();
      if (newTask) {
        $('#comment_block').append(`<p>${newTask}</p>`);
        $(this).val("");
      }
    }
  });
});
$('#id_comment_text').on('keypress', function (event) {
    if (event.keyCode == 13) {
        let content = this.value;  
        let caret = getCaret(this);          
        this.value = content.substring(0, caret - 1) + "\n" + content.substring(caret, content.length);
        event.stopPropagation();
        
    };
});
</script>
<form class=" " action="% url 'articles:leave_comment' slug=article.slug %" method="post">

  {% csrf_token %}

  <input type="text" required placeholder="Your name" name="name" ><br>
  <textarea name="text" required=" " placeholder="Text of comment" rows="10" cols="55">
  </textarea><br>

  <button type="submit" name="button">Leave comment</button>

</form>-->

blogs_app_fi/mysite/apps/articles/templates/articles/homepage.html
{% extends 'base.html' %}
{% block content %}
<title>My articles</title>
<style>

    #asterisk{
      float: right;
    }

</style>

{% if articles %}
  {% for a in articles %}

  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ a.author_article.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" id="author_name" href="{% url 'articles:user_articles' a.author_article.username %}">
          {{ a.author_article }}</a>

        <small class="text-muted">{{ a.pub_date }}</small>

              <small class="text-muted" id="asterisk">
                *click on title of article to see details</small>
      </div>
    <h2 class="article-title"><a class="article-title" href="{% url 'articles:detail' slug=a.slug %}" style="word-wrap:normal;">
      {{ a.article_title }}</a></h2>
    <p class="article-content">{{ a.snippet }}</p>
    </div>
  </article>

  {% endfor %}
{% else %}
    No articles found )=
{% endif %}

{% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" id="pgntr_btn" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" id="pgntr_btn" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" id="pgntr_btn" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
          <a class="btn btn-outline-info mb-4" id="pgntr_btn" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" id="pgntr_btn" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" id="pgntr_btn" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}





{% endblock %}

blogs_app_fi/mysite/apps/articles/templates/articles/list_rubrics.html
{% extends 'base.html' %}
{% block content %}
  <title>Rubrics list</title>
  {% if rubrics %}
    {% for rubric in rubrics %}
    <div class="content-section">
      <h2><a class="article-title" href="{% url 'articles:by_rubric' rubric.rubric_slug %}">{{rubric.rubric_name}}</a>
      </h2>
    </div>
    {% endfor %}
  {% else %}
      No rubrics found! )=
  {% endif %}

{% endblock %}