blogs_app_fi/mysite/apps/articles/urls.py
from django.urls import path
from . import views
from .views import (
    PostUpdateView,
    PostDeleteView,
    ArticleListView,
    UserArticlesListView,
    RubricArticlesListView,
    Comment_delete, 
    Comment_update,
    PostCreateView,)
    #MyCommentDeleteView)


app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='articles_home'), #views.home_page
    path('user/<str:username>/', UserArticlesListView.as_view(), name='user_articles'), #views.home_page and accounts_views.profile
    path('about/', views.about, name = 'articles_about'),
    path('rubrics/', views.list_rubrics, name='list_rubrics'),
    path('rubrics/<slug:rubric_slug>/', RubricArticlesListView.as_view(), name='by_rubric'),
    path('articles/<slug:slug>/', views.detail, name='detail'),
    #path('articles/<slug:slug>/update', views.update_article, name='update_article'),
    path('articles/<slug:slug>/update/', PostUpdateView.as_view(), name='article_update'),
    path('articles/<slug:slug>/delete/', PostDeleteView.as_view(), name='article_delete'),
    path('articles/<int:pk>/comment_delete/', Comment_delete.as_view(), name='comment_delete'),
    path('articles/<int:pk>/comment_update/', Comment_update.as_view(), name='comment_update'),
    #path('articles/<slug:slug>/leave_comment', views.leave_comment, name='leave_comment'),
    path('create_article/', PostCreateView.as_view(), name='create_article'),
    #path('create_article/', views.create_article, name='create_article'),


]






































#{% for rubric in rubrics %}
#<menu>
#<li><a href="{% url 'by_rubric' rubric.pk %}">{{Rubric.name_of_rubric}}</a></li>
#</menu>
#{% endfor %}

#{% endblock %}

blogs_app_fi/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)
#from django.conf.urls import handler400, handler403, handler404, handler500
from django.urls import path, include
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls, name='admin'),
    
    # Password reset block
    path('password_reset/',
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password_reset_complete',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    # ending

    path('captcha/', include('captcha.urls')),

    # custom

    # articles app
    path('', include('articles.urls')),

    # accounts app
    path('profile_settings/', accounts_views.profile_settings, name='profile_settings'),
    path('signup/', accounts_views.signup_view, name='signup'),
    path('login/', accounts_views.login_view,
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
        name='logout'),
]





if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)


handler404 = 'mysite.errors.not_found'

handler400 = 'mysite.errors.bad_request'

handler500 = 'mysite.errors.server_error'

blogs_app_fi/mysite/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #email = models.EmailField(unique=True, max_length=70)
    image = models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')
    info = models.TextField('Write something about your self', blank=True, max_length = 375)

    def __str__(self):
        return f'{self.user.username.capitalize()} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

blogs_app_fi/mysite/apps/articles/models.py
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse
# from emoji_picker.widgets import EmojiPickerTextInputAdmin, EmojiPickerTextareaAdmin


class Article(models.Model):
    article_title = models.CharField('title of article', max_length = 70)
    article_text = models.TextField('text of article')
    slug = models.SlugField(unique = True)
    author_article = models.ForeignKey(User, on_delete=models.CASCADE)
    rubric = models.ForeignKey('Rubric', null = True, on_delete = models.PROTECT, blank=True)
    pub_date = models.DateTimeField('date of publication', auto_now_add = True)
    image = models.ImageField('image', blank=True, upload_to='articles_images')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 1))

    def get_absolute_url(self):
        return reverse('articles:detail', args=[self.slug])

    def snippet(self):
        if len(self.article_text) >= 500: 
            return self.article_text[:500] + '...'
        else: 
            return self.article_text

    '''class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'''

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_comment = models.ForeignKey(User, on_delete = models.CASCADE)
    comment_text = models.TextField('comment text', max_length = 800)
    pub_date = models.DateTimeField('date of publication', auto_now_add = True)

    '''def __str__(self):
        return self.author_name'''


    '''class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'''


class Rubric(models.Model):
    rubric_name = models.CharField(max_length=50, unique=True)
    rubric_slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.rubric_name

blogs_app_fi/mysite/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from captcha.fields import CaptchaField
from django.contrib import messages
#from emoji_picker.widgets import EmojiPickerTextInput, EmojiPickerTextarea

class UserSignupForm(UserCreationForm):
    #username = forms.CharField(required=True, max_length=21)
    #email = forms.EmailField(required=True, max_length = 75)
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_count = User.objects.filter(email=email).count()
        if user_count > 0:
            raise forms.ValidationError("This email has already been registered.")
        return email


class UserUpdateForm(forms.ModelForm):
    #username = forms.CharField(widget=EmojiPickerTextInput)
    #email = forms.CharField(widget=EmojiPickerTextInput)
    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user_count = User.objects.filter(username=username).count()
        if user_count > 1:
            raise forms.ValidationError("This username has already been registered.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_count = User.objects.filter(email=email).count()
        if user_count > 1:
            raise forms.ValidationError("This email has already been registered.")
        return email

class ProfileUpdateForm(forms.ModelForm):
    #info = forms.CharField(widget=EmojiPickerTextarea)
    class Meta:
        model = Profile
        fields = ['image', 'info']

blogs_app_fi/mysite/apps/articles/forms.py
from django import forms
from . import models

'''class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['article_title', 'article_text', 'slug', 'rubric', 'image']
'''

class LeaveComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['comment_text']
        # class Media:
        #     js = ('js/enter.js', )

blogs_app_fi/mysite/apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserSignupForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import Http404, HttpResponseRedirect, HttpResponse

def signup_view(request):
    if request.user.is_authenticated:
        return redirect('articles:articles_home')
    else:
        if request.method == 'POST': # if you want to make new user
            form = UserSignupForm(request.POST) # sending request to server
            if form.is_valid(): # if username is free, etc.
                username = form.cleaned_data.get('username').capitalize()
                messages.success(request, f'Account created for {username}! Now you able to login')
                user = form.save()#.capitalize() # save on server
                return redirect('login')

        else:
            form = UserSignupForm() # just returning to current page

        return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect('articles:articles_home')
    else:
    # if this is a POST request we need to process the form data
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            form = AuthenticationForm(data=request.POST) # what you fill
            if form.is_valid(): # if passwords are matching, etc.
                user = form.get_user()
                username = form.cleaned_data.get('username').capitalize()
                messages.success(request, 'You are logged in.')
                login(request, user) # log the user in
                if 'next' in request.POST: # if have ?next=
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('articles:articles_home') # if no ?next=
                
            else:
                messages.error(request, "Please, correct mistakes")

        else:
            form = AuthenticationForm() # just returning to current page
        return render(request, 'accounts/login.html', {'form': form})


@login_required
def profile_settings(request):
    context_object_name = 'profile'
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('profile_settings')
        # else:
        #     messages.error(request, 'Please, correct mistakes')
        #     # return redirect('profile_settings')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'accounts/profile_settings.html', context)

blogs_app_fi/mysite/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy			# USE VIRTUAL ENVIRONMENT! blogs_venv\Scripts\activate
											
from django.views.generic import CreateView

from accounts.models import Profile

from .models import (
    Article,
    Rubric,
    Comment
    )

from django.contrib.auth.decorators import login_required

from . import forms

from accounts.forms import UserUpdateForm, ProfileUpdateForm

from django.contrib import messages

from django.views.generic import (
    ListView,
    UpdateView,
    DeleteView
)

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

#from django import forms

#from emoji_picker.widgets import EmojiPickerTextInput, EmojiPickerTextarea


class ArticleListView(ListView):
    model = Article
    ordering = ['-pub_date']
    paginate_by = 3
    template_name = 'articles/homepage.html'
    context_object_name = 'articles'


class UserArticlesListView(ArticleListView, ListView):
    template_name = 'articles/user_posts.html'
    context_object_name = 'user_articles'
    # paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(
        User,
        username=self.kwargs.get('username'))

        return Article.objects.filter(author_article=user)#.order_by('-pub_date')


def about(request):
	return render(request, 'articles/about.html')


#@login_required
def detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    last_comments_list = article.comment_set.order_by('-pub_date') # view 10 last comms
    new_comment = None
    image = article.image
    # Comment posted
    if request.method == 'POST':
        comment_form = forms.LeaveComment(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # get username
            new_comment.author_comment = request.user
            # Assign the current post to the comment
            new_comment.article = article
            # Save the comment to the database
            new_comment.save()
            messages.success(request, 'You created a comment!')
            return HttpResponseRedirect( reverse('articles:detail', args = (article.slug,))
            ) # doing it on fly, set the comment to article

    else:
        comment_form = forms.LeaveComment()

    return render(request, 'articles/detail.html', {'article': article,
                                                    'last_comments_list': last_comments_list,
                                                    'new_comment': new_comment,
                                                    'comment_form': comment_form,
                                                    'image': image})


# Rubrics Stuff

def list_rubrics(request):
	rubrics = Rubric.objects.all()
	return render(request, 'articles/list_rubrics.html', {
	'rubrics': rubrics
	})


class RubricArticlesListView(ListView):
    model = Rubric
    template_name = 'articles/by_rubric.html'
    context_object_name = 'by_rubric'
    ordering = ['-pub_date']
    paginate_by = 5

    def get_queryset(self):
        by_rubric = get_object_or_404(
        Rubric,
        #rubric_name=self.kwargs.get('rubric_name'),
        rubric_slug=self.kwargs.get('rubric_slug'))

        return Article.objects.filter(rubric_id=by_rubric).order_by('-pub_date')


class Post(LoginRequiredMixin):
    model = Article

    def form_valid(self, form):
        form.instance.author_article = self.request.user
        return super().form_valid(form)

    def test_func(self):                   #checking user
        post = self.get_object()
        if self.request.user == post.author_article:
            return True
        return False

class PostCreateView(Post, CreateView):
    fields = ['article_title', 'article_text', 'slug', 'rubric', 'image']

    def get_success_url(self):
        messages.success(self.request, 'You created an article')
        return reverse_lazy('articles:detail', kwargs={'slug': self.object.slug})


class PostUpdateView(Post, UserPassesTestMixin, UpdateView):
	fields = ['article_title', 'article_text', 'rubric', 'image']


class PostDeleteView(Post, UserPassesTestMixin, DeleteView):
    success_url = reverse_lazy('articles:articles_home')


class Comment_view(LoginRequiredMixin, UserPassesTestMixin):
    model = Comment

    def test_func(self):                   #checking user
        post = self.get_object()
        if self.request.user == post.author_comment:
            return True
        return False

class Comment_delete(Comment_view, DeleteView):

    def get_success_url(self):
        messages.error(self.request, 'You deleted a comment.')
        return reverse_lazy('articles:detail', kwargs={'slug': self.object.article.slug})


class Comment_update(Comment_view, UpdateView):
    fields = ['comment_text']

    def get_success_url(self):
        messages.info(self.request, 'You updated a comment.')
        return reverse_lazy('articles:detail', kwargs={'slug': self.object.article.slug})

    def form_valid(self, form):
        form.instance.author_comment = self.request.user
        return super().form_valid(form)

blogs_app_fi/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="theme-light">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/main.css' %}" id="theme-link">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'assets/dark.css' %}"> -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    
    <link rel="icon" href="{% static 'assets/snake.ico'%}" type="image/x-icon"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
<style>
    
  
</style>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'articles:articles_home' %}">Articles</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'articles:articles_home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'articles:articles_about' %}">About us</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav" id="header">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'articles:create_article' %}">Create Post</a>
              <a class="nav-item nav-link" href="{% url 'articles:user_articles' user.username %}" id='username_top'>My profile</a>
              <!-- <a class="nav-item nav-link" id="logout" href="{% url 'logout' %}">Logout</a> -->
              {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'signup' %}">Sighup</a>
              {% endif %}
              <!-- <a style="visibility: hidden;">asd</a> -->
              
            </div>
            
          </div>
        </div>
        <button id="theme-button" onclick="toggleTheme()" style="position: absolute; right:1px;"></button>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
          {% for message in messages %}
              {% if not message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                  {{ message }}
                </div>
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" role="alert">
                  ❌ &nbsp;{{ message }}</div>
              {% endif %}
          {% endfor %}
          {% endif %}
          
          {% block content %}
          {% endblock %}
          
        </div>
        <div class="col-md-4">
          <!-- <div class="content-section"></div>
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.</p>
              <div class="col-4"> -->
                  <aside class="list-group" id="sidebar" role="tablist">
                    <a class="list-group-item list-group-item-action" id="list-item" href="{% url 'articles:list_rubrics' %}" role="tab">Rubrics</a>
                    {% if user.is_authenticated %}
                    <a class="list-group-item list-group-item-action" id="list-item" href="{% url 'profile_settings' %}" role="tab">Settings</a>
                    <!-- <a class="list-group-item list-group-item-action" id="list-item"  href="{% url 'articles:user_articles' user.username %}" role="tab">Profile</a>
                    <a class="list-group-item list-group-item-action" id="list-item" href="#list-messages" role="tab">Messages</a> -->
                    {% endif %}
                  </aside>
                  
                  <button id="scrollToTop"></button>
        </div>
      </div>
    </main>
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js'%}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <script src="{% static 'js/profile_for_others.js' %}"> </script>
    <script src="{% static 'js/themes.js' %}"></script>

    <script>
      $(function() {
    let btn = $('#scrollToTop');

    $(window).scroll(function() {
      if ($(window).scrollTop() > 300) {
        btn.addClass('show');
      } else {
        btn.removeClass('show');
      }
    });

    btn.on('click', function(e) {
      e.preventDefault();
      $('html, body').animate({scrollTop:0}, '300');
    });
  });

    </script>

    
    
    <script>
      if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
        let header = document.getElementById("header");
        let sidebar = document.getElementById("sidebar");
        while (sidebar.hasChildNodes()) header.appendChild(sidebar.firstChild).className = "nav-item nav-link";
        $(sidebar).remove();
      }
      $("#asterisk.text-muted").remove();
      // $(function(){
      //       let image = $("#id_image"); 
      //       image.button = className = "btn btn-secondary";
      //   });
        // $("body").style = "margin: 5rem;"
  // else{
      //   document.getElementById("comment_block").style.maxWidth = "650px";
      //   };
      </script>
      <script>
      // function to set a given theme/color-scheme
        function setTheme(themeName) {
            localStorage.setItem('theme', themeName);
            document.documentElement.className = themeName;
        }
        
        // function to toggle between light and dark theme
        function toggleTheme() {
            if (localStorage.getItem('theme') === 'theme-dark') {
                setTheme('theme-light');
                if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
                  $("#header").append($("#theme-button"));
                  $("#theme-button").html("<span class='nav-item nav-link'>Light mode</span>");
                }
                else{ $("#theme-button").html("<span class='nav-item nav-link'>Light mode ☀️</span>")
                }
                }
            else {
                setTheme('theme-dark');
                if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
                $("#header").append($("#theme-button"));
                $("#theme-button").html("<span class='nav-item nav-link'>Dark mode</span>");

                  
              }
                else{ $("#theme-button").html("<span class='nav-item nav-link'>Dark mode 🌙</span>")
                }
                }
            }
        
        
        // Immediately invoked function to set the theme on initial load
        (function () {
            if (localStorage.getItem('theme') === 'theme-dark') {
                setTheme('theme-dark');
                if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
                $("#header").append($("#theme-button"));
                $("#theme-button").html("<span class='nav-item nav-link'>Dark mode</span>");
                  
              }
                else{ $("#theme-button").html("<span class='nav-item nav-link'>Dark mode 🌙</span>")
                }
                }
            
                
            else {
                setTheme('theme-light');
                if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
                  $("#header").append($("#theme-button"));
                  $("#theme-button").html("<span class='nav-item nav-link'>Light mode</span>");
                }
                else{ $("#theme-button").html("<span class='nav-item nav-link'>Light mode ☀️</span>")
                }
                }           
        })();
        </script>
</body>
</html>