blogs_app_fi/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)
#from django.conf.urls import handler400, handler403, handler404, handler500
from django.urls import path, include
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls, name='admin'),
    
    # Password reset block
    path('password_reset/',
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password_reset_complete',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    # ending

    path('captcha/', include('captcha.urls')),

    # custom

    # articles app
    path('', include('articles.urls')),

    # accounts app
    path('profile_settings/', accounts_views.profile_settings, name='profile_settings'),
    path('signup/', accounts_views.signup_view, name='signup'),
    path('login/', accounts_views.login_view,
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
        name='logout'),
]





if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)


handler404 = 'mysite.errors.not_found'

handler400 = 'mysite.errors.bad_request'

handler500 = 'mysite.errors.server_error'

blogs_app_fi/mysite/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #email = models.EmailField(unique=True, max_length=70)
    image = models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')
    info = models.TextField('Write something about your self', blank=True, max_length = 375)

    def __str__(self):
        return f'{self.user.username.capitalize()} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

blogs_app_fi/mysite/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from captcha.fields import CaptchaField
from django.contrib import messages
#from emoji_picker.widgets import EmojiPickerTextInput, EmojiPickerTextarea

class UserSignupForm(UserCreationForm):
    #username = forms.CharField(required=True, max_length=21)
    #email = forms.EmailField(required=True, max_length = 75)
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_count = User.objects.filter(email=email).count()
        if user_count > 0:
            raise forms.ValidationError("This email has already been registered.")
        return email


class UserUpdateForm(forms.ModelForm):
    #username = forms.CharField(widget=EmojiPickerTextInput)
    #email = forms.CharField(widget=EmojiPickerTextInput)
    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user_count = User.objects.filter(username=username).count()
        if user_count > 1:
            raise forms.ValidationError("This username has already been registered.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_count = User.objects.filter(email=email).count()
        if user_count > 1:
            raise forms.ValidationError("This email has already been registered.")
        return email

class ProfileUpdateForm(forms.ModelForm):
    #info = forms.CharField(widget=EmojiPickerTextarea)
    class Meta:
        model = Profile
        fields = ['image', 'info']

blogs_app_fi/mysite/apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserSignupForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import Http404, HttpResponseRedirect, HttpResponse

def signup_view(request):
    if request.user.is_authenticated:
        return redirect('articles:articles_home')
    else:
        if request.method == 'POST': # if you want to make new user
            form = UserSignupForm(request.POST) # sending request to server
            if form.is_valid(): # if username is free, etc.
                username = form.cleaned_data.get('username').capitalize()
                messages.success(request, f'Account created for {username}! Now you able to login')
                user = form.save()#.capitalize() # save on server
                return redirect('login')

        else:
            form = UserSignupForm() # just returning to current page

        return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect('articles:articles_home')
    else:
    # if this is a POST request we need to process the form data
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            form = AuthenticationForm(data=request.POST) # what you fill
            if form.is_valid(): # if passwords are matching, etc.
                user = form.get_user()
                username = form.cleaned_data.get('username').capitalize()
                messages.success(request, 'You are logged in.')
                login(request, user) # log the user in
                if 'next' in request.POST: # if have ?next=
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('articles:articles_home') # if no ?next=
                
            else:
                messages.error(request, "Please, correct mistakes")

        else:
            form = AuthenticationForm() # just returning to current page
        return render(request, 'accounts/login.html', {'form': form})


@login_required
def profile_settings(request):
    context_object_name = 'profile'
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('profile_settings')
        # else:
        #     messages.error(request, 'Please, correct mistakes')
        #     # return redirect('profile_settings')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'accounts/profile_settings.html', context)

blogs_app_fi/mysite/apps/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Login</title>
  <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
          {% if request.GET.next %}
          <input type="hidden" name="next" value="{{ request.GET.next }}"/>
          {% endif %}
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Login</button>
          </div>
    </form>
      <div class="border-top pt-3">
        <small class="text-muted">
            Haven't got account yet? <a class="ml-2" href="{% url 'signup' %}">Sign Up</a>
            <br>
            Forgot password? <a class="ml-2" href="{% url 'password_reset' %}">Reset password</a>
        </small>
      </div>
  </div>
{% endblock %}

blogs_app_fi/mysite/apps/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Log out</title>

      <h2>You have been logged out</h2>

        <div class="border-top pt-3">
            <small class="text-muted">
              <a href="{% url 'login' %}">Log In Again</a>
            </small>
        </div>

{% endblock %}

blogs_app_fi/mysite/apps/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Password Reset</title>
  <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
          </div>
    </form>
  </div>
{% endblock %}

blogs_app_fi/mysite/apps/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Password Reset Complete</title>
      <div class="alert alert-info">
        Password has been updated!
      </div>
      <a href="{% url 'login' %}">Sigh in here</a>
{% endblock %}

blogs_app_fi/mysite/apps/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Password Reset</title>
  <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Reset Password</button>
          </div>
    </form>
  </div>
{% endblock %}

blogs_app_fi/mysite/apps/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Password Reset</title>
      <div class="alert alert-info">
        An email has been sent with instructions to reset your password!
      </div>

{% endblock %}

blogs_app_fi/mysite/apps/accounts/templates/accounts/profile_for_others.html
<!-- {% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
    </div>
{% endblock %} -->

blogs_app_fi/mysite/apps/accounts/templates/accounts/profile_settings.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
  #asterisk{
    float: right;
  }
  
  #profile_info{
    font-size: 20px;
  }

  #logout{
    /* right: 3%;
    position: absolute; */
    float: right;
  }

</style>
<title>{{ user.username }}</title> 

    <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <small class="text-muted" id="asterisk">*pre-view</small>
        <h2 class="account-heading" id='username_profile'>{{ user.username }}</h2>
        <p id="profile_info">{{ user.profile.info }}</p>
      </div>
    </div>
  </div>
<div>
  <div class="content-section">
    <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="mb-4">Profile Settings</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit" id="update">Update</button>
              <a class="btn btn-outline-danger" id="logout" href="{% url 'logout' %}">Logout</a>
          </div>
      </form>                                 
  </div>   
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
<script>
  let image = document.querySelector("input[type=file]"); 
  image.style = "display: none; position:absolute";  
  let currently = document.querySelector("#div_id_image > div")
  currently.style = "display:none;";
  let label = document.querySelector("#div_id_image > label")
  $(label).html("<span style=color:--select-image><i class=material-icons>add_photo_alternate&nbsp</i>Select an image</span>");
  label.className = "btn btn-secondary";
  label.style = "margin-bottom: -8px;font-size: 20px;";
  // let allDiv = document.querySelector("#div_id_image");
  // $(allDiv).append("<span style='margin-bottom:-10px'>Image</span>")
</script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
    <script src="{% static 'js/fgEmojiPicker.js' %}" ></script>
    <script>
        let inputComment = document.querySelector("#div_id_info > div")
    $(inputComment).append("<button type=button class=emoji style=top:-30px;right:5px;float:right;position:relative;>😎</button>")
</script>

<script>
  new FgEmojiPicker({
            trigger: ['.emoji'],
            position: ['bottom', 'right'],
            dir: '/static/js/',
            emit(obj, triggerElement) {
                const emoji = obj.emoji;
                document.querySelector('#id_info').value += emoji;
                
            }
        });
</script>
{% endblock %}

blogs_app_fi/mysite/apps/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<title>Join Today</title>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Log In</a>
            </small>
        </div>
    </div>
{% endblock %}